---

- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Learn Genie - 1st Run
    learn_genie:
      host: "{{ ansible_host }}"
      port: 8181
      protocol: ssh
      username: admin
      password: Admin_1234!
      os: nxos
      feature: ospf
    register: genie1

#  - name: Debug Genie
#    debug:
#      msg: "{{ genie_arp1 }}"

  - name: pause for changes
    pause:
      minutes: 1

  - name: Learn Genie with Diff
    learn_genie:
      host: "{{ ansible_host }}"
      port: 8181
      protocol: ssh
      username: admin
      password: Admin_1234!
      os: nxos
      feature: ospf
      compare_to: "{{ genie1 }}"
    diff: true

#  - name: Debug2
#    debug:
#      msg: "{{ genie2 }}"
