---

- hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Test Learn Genie
    learn_genie:
      host: "{{ ansible_host }}"
      port: 8181
      protocol: ssh
      username: admin
      password: Admin_1234!
      os: nxos
      feature: "{{ feature }}"
    register: genie1

  - name: Debug1
    debug:
      msg: "{{ genie1 }}"

  - name: Test Learn Genie 2
    learn_genie:
      host: "{{ ansible_host }}"
      port: 8181
      protocol: ssh
      username: admin
      password: Admin_1234!
      os: nxos
      feature: "{{ feature }}"
      compare_to: "{{ genie1 }}"
      # exclude: "{{ ['in_requests_pkts'] }}"
      no_default_exclusion: true
      colors: false
    register: genie2
    diff: false

  - name: Debug2
    debug:
      msg: "{{ genie2 }}"
